// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCish3mCEhgtXKOO5LS5AZUVhzgWIs_I98',
    appId: '1:105392704715:web:7d98b9cc698abf45981f4e',
    messagingSenderId: '105392704715',
    projectId: 'ujksmarthome',
    authDomain: 'ujksmarthome.firebaseapp.com',
    storageBucket: 'ujksmarthome.appspot.com',
    measurementId: 'G-8QBE2CMLP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEnbGsiI9BShw2pWdq0R0msYWuAxhIAJw',
    appId: '1:105392704715:android:e59b963caa924b45981f4e',
    messagingSenderId: '105392704715',
    projectId: 'ujksmarthome',
    storageBucket: 'ujksmarthome.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYCVMlv5Wo-DWUJvjVAb3yR3PhedrAik8',
    appId: '1:105392704715:ios:dd931dce601c4011981f4e',
    messagingSenderId: '105392704715',
    projectId: 'ujksmarthome',
    storageBucket: 'ujksmarthome.appspot.com',
    iosBundleId: 'com.example.flutterAppSmarthome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYCVMlv5Wo-DWUJvjVAb3yR3PhedrAik8',
    appId: '1:105392704715:ios:4eacc00ae387468d981f4e',
    messagingSenderId: '105392704715',
    projectId: 'ujksmarthome',
    storageBucket: 'ujksmarthome.appspot.com',
    iosBundleId: 'com.example.flutterAppSmarthome.RunnerTests',
  );
}
